# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rosserial_arduino/command.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class command(genpy.Message):
  _md5sum = "e50c6157766eba7ad5bf8e5e1c37c251"
  _type = "rosserial_arduino/command"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 lwheel_vtarget
float32 rwheel_vtarget
int16 mode

"""
  __slots__ = ['lwheel_vtarget','rwheel_vtarget','mode']
  _slot_types = ['float32','float32','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       lwheel_vtarget,rwheel_vtarget,mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(command, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.lwheel_vtarget is None:
        self.lwheel_vtarget = 0.
      if self.rwheel_vtarget is None:
        self.rwheel_vtarget = 0.
      if self.mode is None:
        self.mode = 0
    else:
      self.lwheel_vtarget = 0.
      self.rwheel_vtarget = 0.
      self.mode = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2fh.pack(_x.lwheel_vtarget, _x.rwheel_vtarget, _x.mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.lwheel_vtarget, _x.rwheel_vtarget, _x.mode,) = _struct_2fh.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2fh.pack(_x.lwheel_vtarget, _x.rwheel_vtarget, _x.mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.lwheel_vtarget, _x.rwheel_vtarget, _x.mode,) = _struct_2fh.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2fh = struct.Struct("<2fh")
