# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rosserial_arduino/Imu.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Imu(genpy.Message):
  _md5sum = "bad5905c0c2a9b4ef7e4da9282519ce1"
  _type = "rosserial_arduino/Imu"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 accelX 
float32 accelY
float32 accelZ
float32 gyroX
float32 gyroY
float32 gyroZ
float32 compassX
float32 compassY
float32 compassZ

"""
  __slots__ = ['accelX','accelY','accelZ','gyroX','gyroY','gyroZ','compassX','compassY','compassZ']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       accelX,accelY,accelZ,gyroX,gyroY,gyroZ,compassX,compassY,compassZ

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Imu, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.accelX is None:
        self.accelX = 0.
      if self.accelY is None:
        self.accelY = 0.
      if self.accelZ is None:
        self.accelZ = 0.
      if self.gyroX is None:
        self.gyroX = 0.
      if self.gyroY is None:
        self.gyroY = 0.
      if self.gyroZ is None:
        self.gyroZ = 0.
      if self.compassX is None:
        self.compassX = 0.
      if self.compassY is None:
        self.compassY = 0.
      if self.compassZ is None:
        self.compassZ = 0.
    else:
      self.accelX = 0.
      self.accelY = 0.
      self.accelZ = 0.
      self.gyroX = 0.
      self.gyroY = 0.
      self.gyroZ = 0.
      self.compassX = 0.
      self.compassY = 0.
      self.compassZ = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_9f.pack(_x.accelX, _x.accelY, _x.accelZ, _x.gyroX, _x.gyroY, _x.gyroZ, _x.compassX, _x.compassY, _x.compassZ))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.accelX, _x.accelY, _x.accelZ, _x.gyroX, _x.gyroY, _x.gyroZ, _x.compassX, _x.compassY, _x.compassZ,) = _struct_9f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_9f.pack(_x.accelX, _x.accelY, _x.accelZ, _x.gyroX, _x.gyroY, _x.gyroZ, _x.compassX, _x.compassY, _x.compassZ))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.accelX, _x.accelY, _x.accelZ, _x.gyroX, _x.gyroY, _x.gyroZ, _x.compassX, _x.compassY, _x.compassZ,) = _struct_9f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_9f = struct.Struct("<9f")
