// Generated by gencpp from file rosserial_arduino/drive.msg
// DO NOT EDIT!


#ifndef ROSSERIAL_ARDUINO_MESSAGE_DRIVE_H
#define ROSSERIAL_ARDUINO_MESSAGE_DRIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosserial_arduino
{
template <class ContainerAllocator>
struct drive_
{
  typedef drive_<ContainerAllocator> Type;

  drive_()
    : velocityX(0.0)
    , velocityY(0.0)
    , velocityW(0.0)  {
    }
  drive_(const ContainerAllocator& _alloc)
    : velocityX(0.0)
    , velocityY(0.0)
    , velocityW(0.0)  {
    }



   typedef float _velocityX_type;
  _velocityX_type velocityX;

   typedef float _velocityY_type;
  _velocityY_type velocityY;

   typedef float _velocityW_type;
  _velocityW_type velocityW;




  typedef boost::shared_ptr< ::rosserial_arduino::drive_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosserial_arduino::drive_<ContainerAllocator> const> ConstPtr;

}; // struct drive_

typedef ::rosserial_arduino::drive_<std::allocator<void> > drive;

typedef boost::shared_ptr< ::rosserial_arduino::drive > drivePtr;
typedef boost::shared_ptr< ::rosserial_arduino::drive const> driveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosserial_arduino::drive_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosserial_arduino::drive_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosserial_arduino

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rosserial_arduino': ['/home/niraj/final_wheelchair_ws/src/rosserial/rosserial_arduino/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosserial_arduino::drive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosserial_arduino::drive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosserial_arduino::drive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosserial_arduino::drive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosserial_arduino::drive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosserial_arduino::drive_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosserial_arduino::drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0adb7866b368a19e280e214c6b1567ad";
  }

  static const char* value(const ::rosserial_arduino::drive_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0adb7866b368a19eULL;
  static const uint64_t static_value2 = 0x280e214c6b1567adULL;
};

template<class ContainerAllocator>
struct DataType< ::rosserial_arduino::drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosserial_arduino/drive";
  }

  static const char* value(const ::rosserial_arduino::drive_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosserial_arduino::drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 velocityX\n\
float32 velocityY\n\
float32 velocityW\n\
";
  }

  static const char* value(const ::rosserial_arduino::drive_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosserial_arduino::drive_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocityX);
      stream.next(m.velocityY);
      stream.next(m.velocityW);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct drive_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosserial_arduino::drive_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosserial_arduino::drive_<ContainerAllocator>& v)
  {
    s << indent << "velocityX: ";
    Printer<float>::stream(s, indent + "  ", v.velocityX);
    s << indent << "velocityY: ";
    Printer<float>::stream(s, indent + "  ", v.velocityY);
    s << indent << "velocityW: ";
    Printer<float>::stream(s, indent + "  ", v.velocityW);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSSERIAL_ARDUINO_MESSAGE_DRIVE_H
