// Generated by gencpp from file rosserial_arduino/Imu.msg
// DO NOT EDIT!


#ifndef ROSSERIAL_ARDUINO_MESSAGE_IMU_H
#define ROSSERIAL_ARDUINO_MESSAGE_IMU_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosserial_arduino
{
template <class ContainerAllocator>
struct Imu_
{
  typedef Imu_<ContainerAllocator> Type;

  Imu_()
    : accelX(0.0)
    , accelY(0.0)
    , accelZ(0.0)
    , gyroX(0.0)
    , gyroY(0.0)
    , gyroZ(0.0)
    , compassX(0.0)
    , compassY(0.0)
    , compassZ(0.0)  {
    }
  Imu_(const ContainerAllocator& _alloc)
    : accelX(0.0)
    , accelY(0.0)
    , accelZ(0.0)
    , gyroX(0.0)
    , gyroY(0.0)
    , gyroZ(0.0)
    , compassX(0.0)
    , compassY(0.0)
    , compassZ(0.0)  {
    }



   typedef float _accelX_type;
  _accelX_type accelX;

   typedef float _accelY_type;
  _accelY_type accelY;

   typedef float _accelZ_type;
  _accelZ_type accelZ;

   typedef float _gyroX_type;
  _gyroX_type gyroX;

   typedef float _gyroY_type;
  _gyroY_type gyroY;

   typedef float _gyroZ_type;
  _gyroZ_type gyroZ;

   typedef float _compassX_type;
  _compassX_type compassX;

   typedef float _compassY_type;
  _compassY_type compassY;

   typedef float _compassZ_type;
  _compassZ_type compassZ;




  typedef boost::shared_ptr< ::rosserial_arduino::Imu_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosserial_arduino::Imu_<ContainerAllocator> const> ConstPtr;

}; // struct Imu_

typedef ::rosserial_arduino::Imu_<std::allocator<void> > Imu;

typedef boost::shared_ptr< ::rosserial_arduino::Imu > ImuPtr;
typedef boost::shared_ptr< ::rosserial_arduino::Imu const> ImuConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosserial_arduino::Imu_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosserial_arduino::Imu_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosserial_arduino

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rosserial_arduino': ['/home/niraj/final_wheelchair_ws/src/rosserial/rosserial_arduino/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosserial_arduino::Imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosserial_arduino::Imu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosserial_arduino::Imu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosserial_arduino::Imu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosserial_arduino::Imu_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosserial_arduino::Imu_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosserial_arduino::Imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bad5905c0c2a9b4ef7e4da9282519ce1";
  }

  static const char* value(const ::rosserial_arduino::Imu_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbad5905c0c2a9b4eULL;
  static const uint64_t static_value2 = 0xf7e4da9282519ce1ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosserial_arduino::Imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosserial_arduino/Imu";
  }

  static const char* value(const ::rosserial_arduino::Imu_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosserial_arduino::Imu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 accelX \n\
float32 accelY\n\
float32 accelZ\n\
float32 gyroX\n\
float32 gyroY\n\
float32 gyroZ\n\
float32 compassX\n\
float32 compassY\n\
float32 compassZ\n\
";
  }

  static const char* value(const ::rosserial_arduino::Imu_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosserial_arduino::Imu_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.accelX);
      stream.next(m.accelY);
      stream.next(m.accelZ);
      stream.next(m.gyroX);
      stream.next(m.gyroY);
      stream.next(m.gyroZ);
      stream.next(m.compassX);
      stream.next(m.compassY);
      stream.next(m.compassZ);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Imu_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosserial_arduino::Imu_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosserial_arduino::Imu_<ContainerAllocator>& v)
  {
    s << indent << "accelX: ";
    Printer<float>::stream(s, indent + "  ", v.accelX);
    s << indent << "accelY: ";
    Printer<float>::stream(s, indent + "  ", v.accelY);
    s << indent << "accelZ: ";
    Printer<float>::stream(s, indent + "  ", v.accelZ);
    s << indent << "gyroX: ";
    Printer<float>::stream(s, indent + "  ", v.gyroX);
    s << indent << "gyroY: ";
    Printer<float>::stream(s, indent + "  ", v.gyroY);
    s << indent << "gyroZ: ";
    Printer<float>::stream(s, indent + "  ", v.gyroZ);
    s << indent << "compassX: ";
    Printer<float>::stream(s, indent + "  ", v.compassX);
    s << indent << "compassY: ";
    Printer<float>::stream(s, indent + "  ", v.compassY);
    s << indent << "compassZ: ";
    Printer<float>::stream(s, indent + "  ", v.compassZ);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSSERIAL_ARDUINO_MESSAGE_IMU_H
